; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -nvptx-atomic-lower | FileCheck %s

; Atomic operations on local memory must be lowered to plain loads and stores
; before instruction selection: PTX has no atomic instructions for the .local
; statespace. This pass runs before AtomicExpand, so even operations wider
; than the maximum supported atomic width (which AtomicExpand would turn into
; libcalls) are expanded.

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64"
target triple = "nvptx64-unknown-unknown"

define double @fadd_local(ptr addrspace(5) %ptr, double %val) {
; CHECK-LABEL: define double @fadd_local(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], double [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    [[NEW:%.*]] = fadd double [[TMP1]], [[VAL]]
; CHECK-NEXT:    store double [[NEW]], ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    ret double [[TMP1]]
;
  %res = atomicrmw fadd ptr addrspace(5) %ptr, double %val monotonic, align 8
  ret double %res
}

define i128 @add_local_i128(ptr addrspace(5) %ptr, i128 %val) {
; CHECK-LABEL: define i128 @add_local_i128(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i128 [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i128, ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    [[NEW:%.*]] = add i128 [[TMP1]], [[VAL]]
; CHECK-NEXT:    store i128 [[NEW]], ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    ret i128 [[TMP1]]
;
  %res = atomicrmw add ptr addrspace(5) %ptr, i128 %val monotonic, align 16
  ret i128 %res
}

define i32 @cmpxchg_local(ptr addrspace(5) %ptr, i32 %cmp, i32 %new) {
; CHECK-LABEL: define i32 @cmpxchg_local(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i32 [[CMP:%.*]], i32 [[NEW:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP1]], [[CMP]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i32 [[NEW]], i32 [[TMP1]]
; CHECK-NEXT:    store i32 [[TMP3]], ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = insertvalue { i32, i1 } poison, i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i32, i1 } [[TMP4]], i1 [[TMP2]], 1
; CHECK-NEXT:    [[RES:%.*]] = extractvalue { i32, i1 } [[TMP5]], 0
; CHECK-NEXT:    ret i32 [[RES]]
;
  %pair = cmpxchg ptr addrspace(5) %ptr, i32 %cmp, i32 %new monotonic monotonic
  %res = extractvalue { i32, i1 } %pair, 0
  ret i32 %res
}

define i128 @cmpxchg_local_i128(ptr addrspace(5) %ptr, i128 %cmp, i128 %new) {
; CHECK-LABEL: define i128 @cmpxchg_local_i128(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i128 [[CMP:%.*]], i128 [[NEW:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i128, ptr addrspace(5) [[PTR]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i128 [[TMP1]], [[CMP]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i128 [[NEW]], i128 [[TMP1]]
; CHECK-NEXT:    store i128 [[TMP3]], ptr addrspace(5) [[PTR]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = insertvalue { i128, i1 } poison, i128 [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i128, i1 } [[TMP4]], i1 [[TMP2]], 1
; CHECK-NEXT:    [[RES:%.*]] = extractvalue { i128, i1 } [[TMP5]], 0
; CHECK-NEXT:    ret i128 [[RES]]
;
  %pair = cmpxchg ptr addrspace(5) %ptr, i128 %cmp, i128 %new monotonic monotonic
  %res = extractvalue { i128, i1 } %pair, 0
  ret i128 %res
}
