; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mcpu=sm_100a -mattr=+ptx86 | FileCheck %s
; RUN: %if ptxas-sm_100a && ptxas-isa-8.6 %{ llc < %s -mcpu=sm_100a -mattr=+ptx86 | %ptxas-verify -arch=sm_100a %}

target triple = "nvptx64-nvidia-cuda"

; MMA accumulators carried across a loop as <2 x float> and passed to inline
; asm as scalars. Even though v2f32 is a legal (packed) register type on
; sm_100+, the accumulators must not round-trip through a 64-bit register on
; each iteration: ptxas heavily penalizes touching MMA accumulator registers
; between an mma fence and the mma instruction, so the mov.b64
; packing/unpacking pairs that would otherwise surround the asm defeat
; accumulator reuse (see https://github.com/llvm/llvm-project/issues/151580).

define ptx_kernel void @acc_loop(ptr addrspace(1) %out, i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1, i32 %n) {
; CHECK-LABEL: acc_loop(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b32 %r<13>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mov.b32 %r9, 0f00000000;
; CHECK-NEXT:    mov.b32 %r8, 0;
; CHECK-NEXT:    ld.param.b32 %r1, [acc_loop_param_7];
; CHECK-NEXT:    ld.param.b32 %r7, [acc_loop_param_6];
; CHECK-NEXT:    ld.param.b32 %r6, [acc_loop_param_5];
; CHECK-NEXT:    ld.param.b32 %r5, [acc_loop_param_4];
; CHECK-NEXT:    ld.param.b32 %r4, [acc_loop_param_3];
; CHECK-NEXT:    ld.param.b32 %r3, [acc_loop_param_2];
; CHECK-NEXT:    ld.param.b32 %r2, [acc_loop_param_1];
; CHECK-NEXT:    ld.param.b64 %rd1, [acc_loop_param_0];
; CHECK-NEXT:    mov.b32 %r10, %r9;
; CHECK-NEXT:    mov.b32 %r11, %r9;
; CHECK-NEXT:    mov.b32 %r12, %r9;
; CHECK-NEXT:  $L__BB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 {%r9,%r10,%r11,%r12}, {%r2,%r3,%r4,%r5}, {%r6,%r7}, {%r9,%r10,%r11,%r12};
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    add.s32 %r8, %r8, 1;
; CHECK-NEXT:    setp.lt.s32 %p1, %r8, %r1;
; CHECK-NEXT:    @%p1 bra $L__BB0_1;
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    st.global.v2.b32 [%rd1], {%r9, %r10};
; CHECK-NEXT:    st.global.v2.b32 [%rd1+8], {%r11, %r12};
; CHECK-NEXT:    ret;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc0 = phi <2 x float> [ zeroinitializer, %entry ], [ %acc0.next, %loop ]
  %acc1 = phi <2 x float> [ zeroinitializer, %entry ], [ %acc1.next, %loop ]
  %c0 = extractelement <2 x float> %acc0, i64 0
  %c1 = extractelement <2 x float> %acc0, i64 1
  %c2 = extractelement <2 x float> %acc1, i64 0
  %c3 = extractelement <2 x float> %acc1, i64 1
  %r = call { float, float, float, float } asm "mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 {$0,$1,$2,$3}, {$4,$5,$6,$7}, {$8,$9}, {$0,$1,$2,$3};", "=f,=f,=f,=f,r,r,r,r,r,r,0,1,2,3"(i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1, float %c0, float %c1, float %c2, float %c3)
  %r0 = extractvalue { float, float, float, float } %r, 0
  %r1 = extractvalue { float, float, float, float } %r, 1
  %r2 = extractvalue { float, float, float, float } %r, 2
  %r3 = extractvalue { float, float, float, float } %r, 3
  %v0 = insertelement <2 x float> poison, float %r0, i64 0
  %acc0.next = insertelement <2 x float> %v0, float %r1, i64 1
  %v1 = insertelement <2 x float> poison, float %r2, i64 0
  %acc1.next = insertelement <2 x float> %v1, float %r3, i64 1
  %i.next = add i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  store <2 x float> %acc0.next, ptr addrspace(1) %out
  %out.8 = getelementptr inbounds i8, ptr addrspace(1) %out, i64 8
  store <2 x float> %acc1.next, ptr addrspace(1) %out.8
  ret void
}
