; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=nvptx64-nvidia-cuda -mcpu=sm_75 | FileCheck %s
; RUN: %if ptxas-sm_75 %{ llc < %s -mtriple=nvptx64-nvidia-cuda -mcpu=sm_75 | %ptxas-verify -arch=sm_75 %}

; The fabs result has a lane whose sign bit is known one before the fabs
; (the constant -1358.0). computeKnownBits for FABS must not report the
; result's sign bit as known one, or the fneg of the extracted lane is
; dropped: fneg(fabs(-1358.0)) must store 0xE54E (58702), not 0x654E.

define void @fabs_fneg_extract(ptr %out, <2 x half> %w, half %p) {
; CHECK-LABEL: fabs_fneg_extract(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<5>;
; CHECK-NEXT:    .reg .b32 %r<4>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [fabs_fneg_extract_param_0];
; CHECK-NEXT:    ld.param.b16 %rs1, [fabs_fneg_extract_param_2];
; CHECK-NEXT:    mov.b32 %r1, {%rs1, %rs2};
; CHECK-NEXT:    and.b32 %r2, %r1, 2147450879;
; CHECK-NEXT:    { .reg .b16 tmp; mov.b32 {%rs3, tmp}, %r2; }
; CHECK-NEXT:    ld.param.b16 %rs4, [fabs_fneg_extract_param_1];
; CHECK-NEXT:    mov.b32 %r3, {%rs3, %rs4};
; CHECK-NEXT:    cvt.u64.u32 %rd2, %r3;
; CHECK-NEXT:    st.b64 [%rd1], %rd2;
; CHECK-NEXT:    st.b64 [%rd1+8], 58702;
; CHECK-NEXT:    ret;
  %v = insertelement <2 x half> <half poison, half -1358.0>, half %p, i64 0
  %abs = call <2 x half> @llvm.fabs.v2f16(<2 x half> %v)
  %shuf = shufflevector <2 x half> %abs, <2 x half> %w, <2 x i32> <i32 0, i32 2>
  %shuf.i = bitcast <2 x half> %shuf to i32
  %shuf.z = zext i32 %shuf.i to i64
  store i64 %shuf.z, ptr %out
  %elt = extractelement <2 x half> %abs, i64 1
  %neg = fneg half %elt
  %neg.i = bitcast half %neg to i16
  %neg.z = zext i16 %neg.i to i64
  %out.1 = getelementptr i8, ptr %out, i64 8
  store i64 %neg.z, ptr %out.1
  ret void
}
