; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; The signature rewrite marks byval kernel arguments readonly. Attributes of
; the original argument (readnone inferred for an unused argument, writeonly
; and initializes for a store-only one, writable) are carried over by
; copyAttributesFrom() and must be dropped, or the verifier rejects the
; attribute combination.
; RUN: opt < %s -mtriple nvptx64 -mcpu=sm_70 -mattr=ptx77 -passes=nvptx-lower-args,verify -S | FileCheck %s

%struct.S = type { i32, i32 }

define ptx_kernel void @unused_arg(ptr readnone byval(%struct.S) align 4 captures(none) %s) {
; CHECK-LABEL: define ptx_kernel void @unused_arg(
; CHECK-SAME: ptr addrspace(101) readonly byval([[STRUCT_S:%.*]]) align 4 captures(none) [[S:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define ptx_kernel void @write_only_arg(ptr writeonly byval(%struct.S) align 4 captures(none) initializes((0, 4)) %s) {
; CHECK-LABEL: define ptx_kernel void @write_only_arg(
; CHECK-SAME: ptr addrspace(101) readonly byval([[STRUCT_S:%.*]]) align 4 captures(none) [[S1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p101.i64(ptr align 4 [[S]], ptr addrspace(101) align 4 [[S1]], i64 8, i1 false)
; CHECK-NEXT:    store i32 1, ptr [[S]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr %s, align 4
  ret void
}

define ptx_kernel void @writable_arg(ptr writable byval(%struct.S) align 4 %s) {
; CHECK-LABEL: define ptx_kernel void @writable_arg(
; CHECK-SAME: ptr addrspace(101) readonly byval([[STRUCT_S:%.*]]) align 4 [[S1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p101.i64(ptr align 4 [[S]], ptr addrspace(101) align 4 [[S1]], i64 8, i1 false)
; CHECK-NEXT:    store i32 1, ptr [[S]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr %s, align 4
  ret void
}
