; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=nvptx64 -mcpu=sm_100 -mattr=+ptx88 -start-after=scalarize-masked-mem-intrin | FileCheck %s
; RUN: %if ptxas-sm_100 && ptxas-isa-8.8 %{ llc < %s -march=nvptx64 -mcpu=sm_100 -mattr=+ptx88 -start-after=scalarize-masked-mem-intrin | %ptxas-verify -arch=sm_100 %}

; The normal pipeline scalarizes masked loads with variable masks before ISel
; (NVPTXTTIImpl::isLegalMaskedLoad only accepts constant masks). Skip that
; pass to check the backend stays sound if such a load reaches it directly:
; with a poison passthru any value is fine in a disabled lane, so the lanes
; with a non-constant mask element are conservatively treated as loaded.

define <4 x float> @global_variable_mask(ptr addrspace(1) %a, <4 x i1> %mask) {
; CHECK-LABEL: global_variable_mask(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [global_variable_mask_param_0];
; CHECK-NEXT:    .pragma "used_bytes_mask 0xffff";
; CHECK-NEXT:    ld.global.v2.b64 {%rd2, %rd3}, [%rd1];
; CHECK-NEXT:    st.param.v2.b64 [func_retval0], {%rd2, %rd3};
; CHECK-NEXT:    ret;
  %v = call <4 x float> @llvm.masked.load.v4f32.p1(ptr addrspace(1) %a, i32 16, <4 x i1> %mask, <4 x float> poison)
  ret <4 x float> %v
}

; A mask that is not a BUILD_VECTOR (here a setcc) provides no per-lane
; information: all bytes are treated as used and the annotation is dropped.
define <4 x float> @global_setcc_mask(ptr addrspace(1) %a, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: global_setcc_mask(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [global_setcc_mask_param_0];
; CHECK-NEXT:    ld.global.v2.b64 {%rd2, %rd3}, [%rd1];
; CHECK-NEXT:    st.param.v2.b64 [func_retval0], {%rd2, %rd3};
; CHECK-NEXT:    ret;
  %m = icmp eq <4 x i32> %x, %y
  %v = call <4 x float> @llvm.masked.load.v4f32.p1(ptr addrspace(1) %a, i32 16, <4 x i1> %m, <4 x float> poison)
  ret <4 x float> %v
}

; A variable mask on a 32-byte load marks all 32 bytes used, which is the
; same encoding as "no annotation".
define <8 x float> @global_variable_mask_v8f32(ptr addrspace(1) %a, <8 x i1> %mask) {
; CHECK-LABEL: global_variable_mask_v8f32(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [global_variable_mask_v8f32_param_0];
; CHECK-NEXT:    ld.global.v4.b64 {%rd2, %rd3, %rd4, %rd5}, [%rd1];
; CHECK-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd4, %rd5};
; CHECK-NEXT:    st.param.v2.b64 [func_retval0], {%rd2, %rd3};
; CHECK-NEXT:    ret;
  %v = call <8 x float> @llvm.masked.load.v8f32.p1(ptr addrspace(1) %a, i32 32, <8 x i1> %mask, <8 x float> poison)
  ret <8 x float> %v
}

; An undef mask element is a disabled lane: its bytes are not marked used.
define <4 x float> @global_undef_mask_element(ptr addrspace(1) %a) {
; CHECK-LABEL: global_undef_mask_element(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [global_undef_mask_element_param_0];
; CHECK-NEXT:    .pragma "used_bytes_mask 0xf00f";
; CHECK-NEXT:    ld.global.v2.b64 {%rd2, %rd3}, [%rd1];
; CHECK-NEXT:    st.param.v2.b64 [func_retval0], {%rd2, %rd3};
; CHECK-NEXT:    ret;
  %v = call <4 x float> @llvm.masked.load.v4f32.p1(ptr addrspace(1) %a, i32 16, <4 x i1> <i1 true, i1 undef, i1 false, i1 true>, <4 x float> poison)
  ret <4 x float> %v
}
