; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=nvptx-ir-peephole -S | FileCheck %s

target triple = "nvptx64-nvidia-cuda"

; A <2 x float> accumulator carried across a loop and only ever taken apart
; into scalars (for the wgmma.mma_async inline asm) and rebuilt from the asm
; results. The PHIs must be split into scalar PHIs so that the accumulator
; does not round-trip through a packed 64-bit register on every iteration.
; The vector is rebuilt right before the store, where unpacking is free.
define void @acc_loop_v2f32(ptr %out, i64 %desca, i64 %descb, i32 %n) {
; CHECK-LABEL: define void @acc_loop_v2f32(
; CHECK-SAME: ptr [[OUT:%.*]], i64 [[DESCA:%.*]], i64 [[DESCB:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_0:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[R0:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_1:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[R1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[R:%.*]] = call { float, float } asm sideeffect "wgmma.mma_async.sync.aligned.m64n8k8.f32.f16.f16 {$0,$1}, $2, $3, 1, 1, 1
; CHECK-NEXT:    [[R0]] = extractvalue { float, float } [[R]], 0
; CHECK-NEXT:    [[R1]] = extractvalue { float, float } [[R]], 1
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_LCSSA_0:%.*]] = phi float [ [[R0]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_LCSSA_1:%.*]] = phi float [ [[R1]], %[[LOOP]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x float> poison, float [[ACC_LCSSA_0]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x float> [[TMP0]], float [[ACC_LCSSA_1]], i64 1
; CHECK-NEXT:    store <2 x float> [[TMP1]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi <2 x float> [ zeroinitializer, %entry ], [ %acc.next, %loop ]
  %lo = extractelement <2 x float> %acc, i64 0
  %hi = extractelement <2 x float> %acc, i64 1
  %r = call { float, float } asm sideeffect "wgmma.mma_async.sync.aligned.m64n8k8.f32.f16.f16 {$0,$1}, $2, $3, 1, 1, 1;", "=f,=f,l,l,0,1"(i64 %desca, i64 %descb, float %lo, float %hi)
  %r0 = extractvalue { float, float } %r, 0
  %r1 = extractvalue { float, float } %r, 1
  %v = insertelement <2 x float> poison, float %r0, i64 0
  %acc.next = insertelement <2 x float> %v, float %r1, i64 1
  %i.next = add i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  %acc.lcssa = phi <2 x float> [ %acc.next, %loop ]
  store <2 x float> %acc.lcssa, ptr %out
  ret void
}

; Same, with <2 x i32> (e.g. mma with s32 accumulators).
define void @acc_loop_v2i32(ptr %out, i64 %desca, i64 %descb, i32 %n) {
; CHECK-LABEL: define void @acc_loop_v2i32(
; CHECK-SAME: ptr [[OUT:%.*]], i64 [[DESCA:%.*]], i64 [[DESCB:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[R0:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_1:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[R1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[R:%.*]] = call { i32, i32 } asm sideeffect "mma.sync.aligned.m8n8k16.row.col.satfinite.s32.s8.s8.s32 {$0,$1}, {$2}, {$3}, {$0,$1}
; CHECK-NEXT:    [[R0]] = extractvalue { i32, i32 } [[R]], 0
; CHECK-NEXT:    [[R1]] = extractvalue { i32, i32 } [[R]], 1
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_LCSSA_0:%.*]] = phi i32 [ [[R0]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_LCSSA_1:%.*]] = phi i32 [ [[R1]], %[[LOOP]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> poison, i32 [[ACC_LCSSA_0]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[ACC_LCSSA_1]], i64 1
; CHECK-NEXT:    store <2 x i32> [[TMP1]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi <2 x i32> [ zeroinitializer, %entry ], [ %acc.next, %loop ]
  %lo = extractelement <2 x i32> %acc, i64 0
  %hi = extractelement <2 x i32> %acc, i64 1
  %r = call { i32, i32 } asm sideeffect "mma.sync.aligned.m8n8k16.row.col.satfinite.s32.s8.s8.s32 {$0,$1}, {$2}, {$3}, {$0,$1};", "=r,=r,l,l,0,1"(i64 %desca, i64 %descb, i32 %lo, i32 %hi)
  %r0 = extractvalue { i32, i32 } %r, 0
  %r1 = extractvalue { i32, i32 } %r, 1
  %v = insertelement <2 x i32> poison, i32 %r0, i64 0
  %acc.next = insertelement <2 x i32> %v, i32 %r1, i64 1
  %i.next = add i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  %acc.lcssa = phi <2 x i32> [ %acc.next, %loop ]
  store <2 x i32> %acc.lcssa, ptr %out
  ret void
}

; A control-flow merge (no loop). Both incoming values are insertelement
; chains; one has a constant base that provides the missing lane.
define float @merge_phi(i1 %c, float %a, float %b) {
; CHECK-LABEL: define float @merge_phi(
; CHECK-SAME: i1 [[C:%.*]], float [[A:%.*]], float [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V_0:%.*]] = phi float [ [[A]], %[[THEN]] ], [ [[B]], %[[ELSE]] ]
; CHECK-NEXT:    [[V_1:%.*]] = phi float [ [[B]], %[[THEN]] ], [ 0.000000e+00, %[[ELSE]] ]
; CHECK-NEXT:    [[SUM:%.*]] = fadd float [[V_0]], [[V_1]]
; CHECK-NEXT:    ret float [[SUM]]
;
entry:
  br i1 %c, label %then, label %else

then:
  %t0 = insertelement <2 x float> poison, float %a, i64 0
  %t1 = insertelement <2 x float> %t0, float %b, i64 1
  br label %merge

else:
  %e0 = insertelement <2 x float> zeroinitializer, float %b, i64 0
  br label %merge

merge:
  %v = phi <2 x float> [ %t1, %then ], [ %e0, %else ]
  %lo = extractelement <2 x float> %v, i64 0
  %hi = extractelement <2 x float> %v, i64 1
  %sum = fadd float %lo, %hi
  ret float %sum
}

; Negative test: the PHI is used by vector arithmetic, so it should stay a
; vector.
define <2 x float> @vector_arith_user(<2 x float> %x, i32 %n) {
; CHECK-LABEL: define <2 x float> @vector_arith_user(
; CHECK-SAME: <2 x float> [[X:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi <2 x float> [ zeroinitializer, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_NEXT]] = fadd <2 x float> [[ACC]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret <2 x float> [[ACC_NEXT]]
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi <2 x float> [ zeroinitializer, %entry ], [ %acc.next, %loop ]
  %acc.next = fadd <2 x float> %acc, %x
  %i.next = add i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret <2 x float> %acc.next
}

; Negative test: extract with a non-constant index.
define float @dynamic_extract(float %a, float %b, i32 %idx, i1 %c) {
; CHECK-LABEL: define float @dynamic_extract(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]], i32 [[IDX:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> poison, float [[A]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <2 x float> [[V0]], float [[B]], i64 1
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = phi <2 x float> [ [[V1]], %[[ENTRY]] ]
; CHECK-NEXT:    [[X:%.*]] = extractelement <2 x float> [[V]], i32 [[IDX]]
; CHECK-NEXT:    ret float [[X]]
;
entry:
  %v0 = insertelement <2 x float> poison, float %a, i64 0
  %v1 = insertelement <2 x float> %v0, float %b, i64 1
  br label %merge

merge:
  %v = phi <2 x float> [ %v1, %entry ]
  %x = extractelement <2 x float> %v, i32 %idx
  ret float %x
}

; Negative test: no extractelement users, only a store; there is no repacking
; to save, so leave it alone.
define void @store_only(ptr %out, float %a, float %b, i1 %c) {
; CHECK-LABEL: define void @store_only(
; CHECK-SAME: ptr [[OUT:%.*]], float [[A:%.*]], float [[B:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> poison, float [[A]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <2 x float> [[V0]], float [[B]], i64 1
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V:%.*]] = phi <2 x float> [ [[V1]], %[[ENTRY]] ], [ zeroinitializer, %[[THEN]] ]
; CHECK-NEXT:    store <2 x float> [[V]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %v0 = insertelement <2 x float> poison, float %a, i64 0
  %v1 = insertelement <2 x float> %v0, float %b, i64 1
  br i1 %c, label %then, label %exit

then:
  br label %exit

exit:
  %v = phi <2 x float> [ %v1, %entry ], [ zeroinitializer, %then ]
  store <2 x float> %v, ptr %out
  ret void
}

; The accumulator is initialized from memory rather than from constants: the
; initial lanes are extracted once in the preheader instead of unpacking the
; PHI on every iteration.
define void @warm_start_loop(ptr %out, ptr %init, i64 %desca, i64 %descb, i32 %n) {
; CHECK-LABEL: define void @warm_start_loop(
; CHECK-SAME: ptr [[OUT:%.*]], ptr [[INIT:%.*]], i64 [[DESCA:%.*]], i64 [[DESCB:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C:%.*]] = load <2 x float>, ptr [[INIT]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[C]], i64 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_0:%.*]] = phi float [ [[TMP0]], %[[ENTRY]] ], [ [[R0:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_1:%.*]] = phi float [ [[TMP1]], %[[ENTRY]] ], [ [[R1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[R:%.*]] = call { float, float } asm sideeffect "wgmma.mma_async.sync.aligned.m64n8k8.f32.f16.f16 {$0,$1}, $2, $3, 1, 1, 1
; CHECK-NEXT:    [[R0]] = extractvalue { float, float } [[R]], 0
; CHECK-NEXT:    [[R1]] = extractvalue { float, float } [[R]], 1
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x float> poison, float [[R0]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x float> [[TMP2]], float [[R1]], i64 1
; CHECK-NEXT:    store <2 x float> [[TMP3]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %c = load <2 x float>, ptr %init
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi <2 x float> [ %c, %entry ], [ %acc.next, %loop ]
  %lo = extractelement <2 x float> %acc, i64 0
  %hi = extractelement <2 x float> %acc, i64 1
  %r = call { float, float } asm sideeffect "wgmma.mma_async.sync.aligned.m64n8k8.f32.f16.f16 {$0,$1}, $2, $3, 1, 1, 1;", "=f,=f,l,l,0,1"(i64 %desca, i64 %descb, float %lo, float %hi)
  %r0 = extractvalue { float, float } %r, 0
  %r1 = extractvalue { float, float } %r, 1
  %v = insertelement <2 x float> poison, float %r0, i64 0
  %acc.next = insertelement <2 x float> %v, float %r1, i64 1
  %i.next = add i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  store <2 x float> %acc.next, ptr %out
  ret void
}

; An insertelement chain based on an unknown vector: the covered lane comes
; from the chain, the uncovered lane is extracted in the incoming block.
define float @vector_base(<2 x float> %x, float %a, i1 %c) {
; CHECK-LABEL: define float @vector_base(
; CHECK-SAME: <2 x float> [[X:%.*]], float [[A:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> [[X]], float [[A]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[X]], i64 1
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V_0:%.*]] = phi float [ [[A]], %[[ENTRY]] ], [ 0.000000e+00, %[[THEN]] ]
; CHECK-NEXT:    [[V_1:%.*]] = phi float [ [[TMP0]], %[[ENTRY]] ], [ 0.000000e+00, %[[THEN]] ]
; CHECK-NEXT:    [[SUM:%.*]] = fadd float [[V_0]], [[V_1]]
; CHECK-NEXT:    ret float [[SUM]]
;
entry:
  %v0 = insertelement <2 x float> %x, float %a, i64 0
  br i1 %c, label %then, label %exit

then:
  br label %exit

exit:
  %v = phi <2 x float> [ %v0, %entry ], [ zeroinitializer, %then ]
  %lo = extractelement <2 x float> %v, i64 0
  %hi = extractelement <2 x float> %v, i64 1
  %sum = fadd float %lo, %hi
  ret float %sum
}

; Negative test: <2 x half> PHIs are packed in a single 32-bit register, which
; is the natural form for them; they are not touched.
define half @v2f16_phi(half %a, half %b, i1 %c) {
; CHECK-LABEL: define half @v2f16_phi(
; CHECK-SAME: half [[A:%.*]], half [[B:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x half> poison, half [[A]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <2 x half> [[V0]], half [[B]], i64 1
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V:%.*]] = phi <2 x half> [ [[V1]], %[[ENTRY]] ], [ zeroinitializer, %[[THEN]] ]
; CHECK-NEXT:    [[LO:%.*]] = extractelement <2 x half> [[V]], i64 0
; CHECK-NEXT:    ret half [[LO]]
;
entry:
  %v0 = insertelement <2 x half> poison, half %a, i64 0
  %v1 = insertelement <2 x half> %v0, half %b, i64 1
  br i1 %c, label %then, label %exit

then:
  br label %exit

exit:
  %v = phi <2 x half> [ %v1, %entry ], [ zeroinitializer, %then ]
  %lo = extractelement <2 x half> %v, i64 0
  ret half %lo
}

; Negative test: an insertelement with a non-constant index cannot be
; resolved to per-lane scalars.
define float @dynamic_insert(float %a, i32 %idx, i1 %c) {
; CHECK-LABEL: define float @dynamic_insert(
; CHECK-SAME: float [[A:%.*]], i32 [[IDX:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> zeroinitializer, float [[A]], i32 [[IDX]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V:%.*]] = phi <2 x float> [ [[V0]], %[[ENTRY]] ], [ zeroinitializer, %[[THEN]] ]
; CHECK-NEXT:    [[LO:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[LO]]
;
entry:
  %v0 = insertelement <2 x float> zeroinitializer, float %a, i32 %idx
  br i1 %c, label %then, label %exit

then:
  br label %exit

exit:
  %v = phi <2 x float> [ %v0, %entry ], [ zeroinitializer, %then ]
  %lo = extractelement <2 x float> %v, i64 0
  ret float %lo
}

; A partially-covering chain whose head has its own extract user: the PHI is
; still scalarized, but the chain must stay live for that user (the lane
; extracted at the end of the entry block would not dominate it).
define float @partial_chain_extra_user(<2 x float> %x, float %a, i1 %c) {
; CHECK-LABEL: define float @partial_chain_extra_user(
; CHECK-SAME: <2 x float> [[X:%.*]], float [[A:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> [[X]], float [[A]], i64 0
; CHECK-NEXT:    [[KEEP:%.*]] = extractelement <2 x float> [[V0]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[X]], i64 1
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V_0:%.*]] = phi float [ [[A]], %[[ENTRY]] ], [ 0.000000e+00, %[[THEN]] ]
; CHECK-NEXT:    [[V_1:%.*]] = phi float [ [[TMP0]], %[[ENTRY]] ], [ 0.000000e+00, %[[THEN]] ]
; CHECK-NEXT:    [[SUM:%.*]] = fadd float [[V_0]], [[KEEP]]
; CHECK-NEXT:    ret float [[SUM]]
;
entry:
  %v0 = insertelement <2 x float> %x, float %a, i64 0
  %keep = extractelement <2 x float> %v0, i64 1
  br i1 %c, label %then, label %exit

then:
  br label %exit

exit:
  %v = phi <2 x float> [ %v0, %entry ], [ zeroinitializer, %then ]
  %lo = extractelement <2 x float> %v, i64 0
  %sum = fadd float %lo, %keep
  ret float %sum
}

; Scalarizing %p makes the chain in %qblock dead, which recursively deletes
; %q -- a candidate PHI that has not been visited yet (it comes later in
; block order). This must not crash.
define float @chain_deletes_later_candidate(float %a, float %b, i1 %c) {
; CHECK-LABEL: define float @chain_deletes_later_candidate(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[QBLOCK:.*]]
; CHECK:       [[MERGE:.*]]:
; CHECK-NEXT:    [[P_0:%.*]] = phi float [ [[A]], %[[QBLOCK]] ], [ 0.000000e+00, %[[QBLOCK2:.*]] ]
; CHECK-NEXT:    [[P_1:%.*]] = phi float [ [[B]], %[[QBLOCK]] ], [ 0.000000e+00, %[[QBLOCK2]] ]
; CHECK-NEXT:    ret float [[P_0]]
; CHECK:       [[QBLOCK]]:
; CHECK-NEXT:    br i1 [[C]], label %[[MERGE]], label %[[QBLOCK2]]
; CHECK:       [[QBLOCK2]]:
; CHECK-NEXT:    br label %[[MERGE]]
;
entry:
  br label %qblock

merge:
  %p = phi <2 x float> [ %chain1, %qblock ], [ zeroinitializer, %qblock2 ]
  %lo = extractelement <2 x float> %p, i64 0
  ret float %lo

qblock:
  %q = phi <2 x float> [ zeroinitializer, %entry ]
  %chain0 = insertelement <2 x float> %q, float %a, i64 0
  %chain1 = insertelement <2 x float> %chain0, float %b, i64 1
  br i1 %c, label %merge, label %qblock2

qblock2:
  br label %merge
}

; Negative test: a cyclic insertelement chain in unreachable code must not
; send the chain walk into an infinite loop.
define float @unreachable_cycle(float %a) {
; CHECK-LABEL: define float @unreachable_cycle(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[DEAD:.*]]:
; CHECK-NEXT:    [[CYC0:%.*]] = insertelement <2 x float> [[CYC1:%.*]], float [[A]], i64 0
; CHECK-NEXT:    [[CYC1]] = insertelement <2 x float> [[CYC0]], float [[A]], i64 1
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = phi <2 x float> [ zeroinitializer, %[[ENTRY]] ], [ [[CYC1]], %[[DEAD]] ]
; CHECK-NEXT:    [[LO:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[LO]]
;
entry:
  br label %merge

dead:
  %cyc0 = insertelement <2 x float> %cyc1, float %a, i64 0
  %cyc1 = insertelement <2 x float> %cyc0, float %a, i64 1
  br label %merge

merge:
  %v = phi <2 x float> [ zeroinitializer, %entry ], [ %cyc1, %dead ]
  %lo = extractelement <2 x float> %v, i64 0
  ret float %lo
}

; Negative test: optnone functions are not touched (the legacy PM skips via
; skipFunction, the new PM via the optnone pass instrumentation).
define float @optnone_phi(<2 x float> %init, i1 %c) noinline optnone {
; CHECK-LABEL: define float @optnone_phi(
; CHECK-SAME: <2 x float> [[INIT:%.*]], i1 [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ACC:%.*]] = phi <2 x float> [ [[INIT]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[LO:%.*]] = extractelement <2 x float> [[ACC]], i64 0
; CHECK-NEXT:    [[HI:%.*]] = extractelement <2 x float> [[ACC]], i64 1
; CHECK-NEXT:    [[S:%.*]] = fadd float [[LO]], [[HI]]
; CHECK-NEXT:    [[NEXT]] = insertelement <2 x float> [[ACC]], float [[S]], i64 0
; CHECK-NEXT:    br i1 [[C]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret float [[S]]
;
entry:
  br label %loop

loop:
  %acc = phi <2 x float> [ %init, %entry ], [ %next, %loop ]
  %lo = extractelement <2 x float> %acc, i64 0
  %hi = extractelement <2 x float> %acc, i64 1
  %s = fadd float %lo, %hi
  %next = insertelement <2 x float> %acc, float %s, i64 0
  br i1 %c, label %loop, label %exit

exit:
  ret float %s
}

; The chain feeding the PHI is built from the PHI's own extracts, and the
; chain head is also stored. The store's rebuilt vector must be wired to the
; values the extracts are replaced with (the scalar PHIs), not to the
; then-erased extracts themselves.
define void @chain_from_own_extracts(ptr %out, i1 %c) {
; CHECK-LABEL: define void @chain_from_own_extracts(
; CHECK-SAME: ptr [[OUT:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[P_0:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[P_0]], %[[LOOP]] ]
; CHECK-NEXT:    [[P_1:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[P_1]], %[[LOOP]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x float> poison, float [[P_0]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x float> [[TMP0]], float [[P_1]], i64 1
; CHECK-NEXT:    store <2 x float> [[TMP1]], ptr [[OUT]], align 8
; CHECK-NEXT:    br i1 [[C]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %p = phi <2 x float> [ zeroinitializer, %entry ], [ %chain1, %loop ]
  %lo = extractelement <2 x float> %p, i64 0
  %hi = extractelement <2 x float> %p, i64 1
  %chain0 = insertelement <2 x float> poison, float %lo, i64 0
  %chain1 = insertelement <2 x float> %chain0, float %hi, i64 1
  store <2 x float> %chain1, ptr %out
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
