; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-simplifylib %s | FileCheck %s

; Constant folding of fast-math library calls (evaluateCall).

declare float @_Z3sinf(float)
declare half @_Z3sinDh(half)
declare double @_Z3sind(double)
declare float @_Z6sincosfPU3AS5f(float, ptr addrspace(5))
declare <2 x float> @_Z3cosDv2_f(<2 x float>)
declare <2 x float> @_Z3powDv2_fS_(<2 x float>, <2 x float>)
declare <2 x float> @_Z4fminDv2_ff(<2 x float>, float)
declare <2 x float> @_Z4fminDv2_fS_(float, <2 x float>)

; The result constant must be rounded to the call's type; sin is evaluated in
; double.
define float @fold_sin_f32() {
; CHECK-LABEL: define float @fold_sin_f32() {
; CHECK-NEXT:    ret float f0x3F576AA4
;
  %r = call fast float @_Z3sinf(float 1.0)
  ret float %r
}

define half @fold_sin_f16() {
; CHECK-LABEL: define half @fold_sin_f16() {
; CHECK-NEXT:    ret half 8.413080e-01
;
  %r = call fast half @_Z3sinDh(half 1.0)
  ret half %r
}

define double @fold_sin_f64() {
; CHECK-LABEL: define double @fold_sin_f64() {
; CHECK-NEXT:    ret double f0x3FEAED548F090CEE
;
  %r = call fast double @_Z3sind(double 1.0)
  ret double %r
}

; The store of the cosine must be a float store, not a double store.
define float @fold_sincos_f32(ptr addrspace(5) %p) {
; CHECK-LABEL: define float @fold_sincos_f32
; CHECK-SAME: (ptr addrspace(5) [[P:%.*]]) {
; CHECK-NEXT:    store float f0x3F0A5140, ptr addrspace(5) [[P]], align 4
; CHECK-NEXT:    ret float f0x3F576AA4
;
  %r = call fast float @_Z6sincosfPU3AS5f(float 1.0, ptr addrspace(5) %p)
  ret float %r
}

define <2 x float> @fold_cos_v2f32() {
; CHECK-LABEL: define <2 x float> @fold_cos_v2f32() {
; CHECK-NEXT:    ret <2 x float> <float f0xBF7D7026, float f0xBF275530>
;
  %r = call fast <2 x float> @_Z3cosDv2_f(<2 x float> <float 3.0, float 4.0>)
  ret <2 x float> %r
}

define <2 x float> @fold_cos_v2f32_zeroinit() {
; CHECK-LABEL: define <2 x float> @fold_cos_v2f32_zeroinit() {
; CHECK-NEXT:    ret <2 x float> splat (float 1.000000e+00)
;
  %r = call fast <2 x float> @_Z3cosDv2_f(<2 x float> zeroinitializer)
  ret <2 x float> %r
}

; A poison lane must not turn the defined lanes into an evaluation at 0.0;
; cos(3.0) is about -0.99, not cos(0.0) == 1.0.
define <2 x float> @no_fold_cos_v2f32_poison_lane() {
; CHECK-LABEL: define <2 x float> @no_fold_cos_v2f32_poison_lane() {
; CHECK-NEXT:    [[R:%.*]] = call fast <2 x float> @_Z3cosDv2_f(<2 x float> <float 3.000000e+00, float poison>)
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %r = call fast <2 x float> @_Z3cosDv2_f(<2 x float> <float 3.0, float poison>)
  ret <2 x float> %r
}

define <2 x float> @no_fold_cos_v2f32_undef_lane() {
; CHECK-LABEL: define <2 x float> @no_fold_cos_v2f32_undef_lane() {
; CHECK-NEXT:    [[R:%.*]] = call fast <2 x float> @_Z3cosDv2_f(<2 x float> <float 3.000000e+00, float undef>)
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %r = call fast <2 x float> @_Z3cosDv2_f(<2 x float> <float 3.0, float undef>)
  ret <2 x float> %r
}

; cos(0.0) hits TDOFold's table (no fast-math flags required), so the poison
; lane is reached; it must not assert, and stays poison in the result.
define <2 x float> @tdofold_cos_v2f32_poison_lane() {
; CHECK-LABEL: define <2 x float> @tdofold_cos_v2f32_poison_lane() {
; CHECK-NEXT:    ret <2 x float> <float 1.000000e+00, float poison>
;
  %r = call <2 x float> @_Z3cosDv2_f(<2 x float> <float 0.0, float poison>)
  ret <2 x float> %r
}

; An undef lane is a defined-but-unknown value, so folding it to poison would
; be wrong; TDOFold just bails.
define <2 x float> @tdofold_cos_v2f32_undef_lane() {
; CHECK-LABEL: define <2 x float> @tdofold_cos_v2f32_undef_lane() {
; CHECK-NEXT:    [[R:%.*]] = call <2 x float> @_Z3cosDv2_f(<2 x float> <float 0.000000e+00, float undef>)
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %r = call <2 x float> @_Z3cosDv2_f(<2 x float> <float 0.0, float undef>)
  ret <2 x float> %r
}

; A poison lane in the exponent must not be evaluated as pow(x, 0.0) == 1.0
; for the defined lanes; pow(3.0, 2.0) is 9.0. (The splat-with-poison
; exponent is still folded, correctly, by the pow(x, 2) => x*x expansion.)
define <2 x float> @pow_v2f32_poison_exp_lane() {
; CHECK-LABEL: define <2 x float> @pow_v2f32_poison_exp_lane() {
; CHECK-NEXT:    ret <2 x float> <float 9.000000e+00, float 1.600000e+01>
;
  %r = call fast <2 x float> @_Z3powDv2_fS_(<2 x float> <float 3.0, float 4.0>, <2 x float> <float 2.0, float poison>)
  ret <2 x float> %r
}

define float @no_fold_sin_f32_undef() {
; CHECK-LABEL: define float @no_fold_sin_f32_undef() {
; CHECK-NEXT:    [[R:%.*]] = call fast float @_Z3sinf(float undef)
; CHECK-NEXT:    ret float [[R]]
;
  %r = call fast float @_Z3sinf(float undef)
  ret float %r
}

; fmin/fmax/ldexp signatures accept an implicitly splatted scalar operand;
; the vector evaluation loop must not treat the scalar as a vector.
define <2 x float> @fmin_v2f32_scalar_second_arg() {
; CHECK-LABEL: define <2 x float> @fmin_v2f32_scalar_second_arg() {
; CHECK-NEXT:    [[R:%.*]] = call fast <2 x float> @llvm.minnum.v2f32(<2 x float> <float 1.000000e+00, float 2.000000e+00>, <2 x float> splat (float 1.500000e+00))
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %r = call fast <2 x float> @_Z4fminDv2_ff(<2 x float> <float 1.0, float 2.0>, float 1.5)
  ret <2 x float> %r
}

define <2 x float> @fmin_v2f32_scalar_first_arg() {
; CHECK-LABEL: define <2 x float> @fmin_v2f32_scalar_first_arg() {
; CHECK-NEXT:    [[R:%.*]] = call fast <2 x float> @llvm.minnum.v2f32(<2 x float> splat (float 1.500000e+00), <2 x float> <float 1.000000e+00, float 2.000000e+00>)
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %r = call fast <2 x float> @_Z4fminDv2_fS_(float 1.5, <2 x float> <float 1.0, float 2.0>)
  ret <2 x float> %r
}
