; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdpal -mcpu=gfx1250 < %s | FileCheck -check-prefix=SDAG %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdpal -mcpu=gfx1250 < %s | FileCheck -check-prefix=GISEL %s

; The carry-out add selects to V_ADD_CO_U32_e64 with the abs64 global address
; as one source. SIFoldOperands must not fold the global by shrinking the add
; to V_ADD_CO_U32_e32, which does not exist on GFX12.

@g = external addrspace(1) global i32

define amdgpu_ps i64 @uaddo_global_base(i64 %ofs) {
; SDAG-LABEL: uaddo_global_base:
; SDAG:       ; %bb.0:
; SDAG-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; SDAG-NEXT:    s_mov_b64 s[0:1], g@abs64
; SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; SDAG-NEXT:    v_add_co_ci_u32_e32 v0, vcc_lo, 0, v0, vcc_lo
; SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; SDAG-NEXT:    v_readfirstlane_b32 s0, v0
; SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; SDAG-NEXT:    ; return to shader part epilog
;
; GISEL-LABEL: uaddo_global_base:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GISEL-NEXT:    s_mov_b64 s[0:1], g@abs64
; GISEL-NEXT:    v_mov_b32_e32 v3, 0
; GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GISEL-NEXT:    v_cndmask_b32_e64 v2, 0, 1, vcc_lo
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GISEL-NEXT:    v_add_nc_u64_e32 v[0:1], v[0:1], v[2:3]
; GISEL-NEXT:    v_readfirstlane_b32 s0, v0
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GISEL-NEXT:    v_readfirstlane_b32 s1, v1
; GISEL-NEXT:    ; return to shader part epilog
  %base = ptrtoint ptr addrspace(1) @g to i64
  %r = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %base, i64 %ofs)
  %sum = extractvalue { i64, i1 } %r, 0
  %ov = extractvalue { i64, i1 } %r, 1
  %ovz = zext i1 %ov to i64
  %out = add i64 %sum, %ovz
  ret i64 %out
}
