; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefixes=GFX9,GFX900 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx950 < %s | FileCheck -check-prefixes=GFX9,GFX950 %s

; @ext_lds is placed by the linker (abs32 relocation), so only the
; addressable LDS size bounds its address.
@ext_lds = external addrspace(3) global [8 x i32], align 4

; On gfx900 (64KB of LDS) the address fits in 16 bits and the shift folds to
; 0. On gfx950 (160KB of addressable LDS) the address may not fit in 16 bits,
; so the shift must survive and keep the relocation.
define i32 @lds_shr16() {
; GFX900-LABEL: lds_shr16:
; GFX900:       ; %bb.0:
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    v_mov_b32_e32 v0, 0
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX950-LABEL: lds_shr16:
; GFX950:       ; %bb.0:
; GFX950-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX950-NEXT:    s_lshr_b32 s0, ext_lds@abs32@lo, 16
; GFX950-NEXT:    v_mov_b32_e32 v0, s0
; GFX950-NEXT:    s_setpc_b64 s[30:31]
  %i = ptrtoint ptr addrspace(3) @ext_lds to i32
  %r = lshr i32 %i, 16
  ret i32 %r
}

; 160KB addresses fit in 18 bits, so this folds to 0 on both targets.
define i32 @lds_shr18() {
; GFX9-LABEL: lds_shr18:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
  %i = ptrtoint ptr addrspace(3) @ext_lds to i32
  %r = lshr i32 %i, 18
  ret i32 %r
}

; The low bits are known zero from the alignment.
define i32 @lds_align_bits() {
; GFX9-LABEL: lds_align_bits:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
  %i = ptrtoint ptr addrspace(3) @ext_lds to i32
  %r = and i32 %i, 3
  ret i32 %r
}
