; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-lower-module-lds < %s | FileCheck %s
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-lower-module-lds,amdgpu-lower-module-lds < %s | FileCheck %s

; The full LTO pipeline runs this pass at link time (so that -lto-partitions
; can split the module afterwards) and then again in the codegen pipeline. The
; second run over already-lowered IR must be a no-op: both RUN lines above must
; produce identical output. See issue #122891.

; Static LDS only used from a kernel, packed into that kernel's struct.
@static.kernel.only = internal addrspace(3) global i64 poison, align 8
@static.kernel.only.2 = internal addrspace(3) global i32 poison, align 4

; Static LDS reachable from two kernels through a function, lowered via the
; module struct or the lookup table depending on strategy.
@static.function = internal addrspace(3) global [8 x i16] poison, align 2

; Dynamic LDS accessed from a function, lowered to per-kernel shadow instances
; plus a lookup table.
@dynamic.function = external hidden addrspace(3) global [0 x float], align 8

; Dynamic LDS only accessed directly from a kernel; left in place by the pass.
@dynamic.kernel.only = external hidden addrspace(3) global [0 x i64], align 8

; Constant LDS is never lowered, so it survives the first run without an
; absolute address. It must not defeat the second run's early exit: without
; that, the rerun rewrites the lowered structs' constantexpr uses into
; instructions and the two RUN lines diverge. Same for LDS with a non-undef
; initializer, which the pass leaves in place for the backend to reject.
@const.lds = internal addrspace(3) constant [4 x i32] undef, align 4
@initialized.lds = internal addrspace(3) global i16 0, align 2

; Static LDS whose address escapes into another global's initializer. The
; lowering rewrites the instruction uses into the kernel struct but cannot
; rewrite the initializer use, so the variable itself survives the first run
; without an absolute address. It must not defeat the early exit either.
@static.escaped = internal addrspace(3) global i32 poison, align 4
@escape.ptr = addrspace(1) global ptr addrspace(3) @static.escaped, align 4

;.
; CHECK: @dynamic.kernel.only = external hidden addrspace(3) global [0 x i64], align 8
; CHECK: @const.lds = internal addrspace(3) constant [4 x i32] undef, align 16
; CHECK: @initialized.lds = internal addrspace(3) global i16 0, align 2
; CHECK: @static.escaped = internal addrspace(3) global i32 poison, align 4
; CHECK: @escape.ptr = addrspace(1) global ptr addrspace(3) @static.escaped, align 4
; CHECK: @llvm.amdgcn.module.lds = internal addrspace(3) global %llvm.amdgcn.module.lds.t poison, align 16, !absolute_symbol [[META0:![0-9]+]]
; CHECK: @llvm.compiler.used = appending addrspace(1) global [1 x ptr] [ptr addrspacecast (ptr addrspace(3) @llvm.amdgcn.module.lds to ptr)], section "llvm.metadata"
; CHECK: @llvm.amdgcn.kernel.k0.lds = internal addrspace(3) global %llvm.amdgcn.kernel.k0.lds.t poison, align 8, !absolute_symbol [[META1:![0-9]+]]
; CHECK: @llvm.amdgcn.k0.dynlds = external addrspace(3) global [0 x i8], align 8, !absolute_symbol [[META2:![0-9]+]]
; CHECK: @llvm.amdgcn.k1.dynlds = external addrspace(3) global [0 x i8], align 8, !absolute_symbol [[META1]]
; CHECK: @llvm.amdgcn.dynlds.offset.table = internal addrspace(4) constant [2 x ptr addrspace(3)] [ptr addrspace(3) @llvm.amdgcn.k0.dynlds, ptr addrspace(3) @llvm.amdgcn.k1.dynlds]
;.
define void @helper() {
; CHECK-LABEL: define void @helper() {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.lds.kernel.id()
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [8 x i16], ptr addrspace(3) @llvm.amdgcn.module.lds, i32 0, i32 3
; CHECK-NEXT:    store i16 1, ptr addrspace(3) [[TMP2]], align 2
; CHECK-NEXT:    [[DYNAMIC_FUNCTION:%.*]] = getelementptr inbounds [2 x ptr addrspace(3)], ptr addrspace(4) @llvm.amdgcn.dynlds.offset.table, i32 0, i32 [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr addrspace(4) [[DYNAMIC_FUNCTION]], align 4
; CHECK-NEXT:    store float 2.000000e+00, ptr addrspace(3) [[TMP3]], align 8
; CHECK-NEXT:    ret void
;
  store i16 1, ptr addrspace(3) getelementptr inbounds ([8 x i16], ptr addrspace(3) @static.function, i32 0, i32 3), align 2
  store float 2.0, ptr addrspace(3) @dynamic.function, align 8
  ret void
}

define amdgpu_kernel void @k0() {
; CHECK-LABEL: define amdgpu_kernel void @k0(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] !llvm.amdgcn.lds.kernel.id [[META3:![0-9]+]] {
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.k0.dynlds) ]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.kernel.k0.lds) ], !alias.scope [[META4:![0-9]+]], !noalias [[META7:![0-9]+]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ]
; CHECK-NEXT:    call void @helper()
; CHECK-NEXT:    store i64 3, ptr addrspace(3) @llvm.amdgcn.kernel.k0.lds, align 8, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    store i32 5, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_K0_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.k0.lds, i32 0, i32 2), align 4, !alias.scope [[META10:![0-9]+]], !noalias [[META11:![0-9]+]]
; CHECK-NEXT:    store i64 4, ptr addrspace(3) @dynamic.kernel.only, align 8
; CHECK-NEXT:    [[C:%.*]] = load i32, ptr addrspace(3) getelementptr inbounds ([4 x i32], ptr addrspace(3) @const.lds, i32 0, i32 2), align 4
; CHECK-NEXT:    store i16 9, ptr addrspace(3) @initialized.lds, align 2
; CHECK-NEXT:    store i32 7, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_K0_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.k0.lds, i32 0, i32 1), align 8, !alias.scope [[META12:![0-9]+]], !noalias [[META13:![0-9]+]]
; CHECK-NEXT:    ret void
;
  call void @helper()
  store i64 3, ptr addrspace(3) @static.kernel.only, align 8
  store i32 5, ptr addrspace(3) @static.kernel.only.2, align 4
  store i64 4, ptr addrspace(3) @dynamic.kernel.only, align 8
  %c = load i32, ptr addrspace(3) getelementptr inbounds ([4 x i32], ptr addrspace(3) @const.lds, i32 0, i32 2), align 4
  store i16 9, ptr addrspace(3) @initialized.lds, align 2
  store i32 7, ptr addrspace(3) @static.escaped, align 4
  ret void
}

define amdgpu_kernel void @k1() {
; CHECK-LABEL: define amdgpu_kernel void @k1(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] !llvm.amdgcn.lds.kernel.id [[META14:![0-9]+]] {
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.k1.dynlds) ]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ]
; CHECK-NEXT:    call void @helper()
; CHECK-NEXT:    ret void
;
  call void @helper()
  ret void
}
;.
; CHECK: attributes #[[ATTR0]] = { "amdgpu-lds-size"="32,32" }
; CHECK: attributes #[[ATTR1]] = { "amdgpu-lds-size"="16,16" }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(none) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
;.
; CHECK: [[META0]] = !{i32 0, i32 1}
; CHECK: [[META1]] = !{i32 16, i32 17}
; CHECK: [[META2]] = !{i32 32, i32 33}
; CHECK: [[META3]] = !{i32 0}
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]]}
; CHECK: [[META6]] = distinct !{[[META6]]}
; CHECK: [[META7]] = !{[[META8:![0-9]+]], [[META9:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], [[META6]]}
; CHECK: [[META9]] = distinct !{[[META9]], [[META6]]}
; CHECK: [[META10]] = !{[[META9]]}
; CHECK: [[META11]] = !{[[META8]], [[META5]]}
; CHECK: [[META12]] = !{[[META8]]}
; CHECK: [[META13]] = !{[[META5]], [[META9]]}
; CHECK: [[META14]] = !{i32 1}
;.
