; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S < %s | FileCheck %s

; isGatherShuffledEntry used to slice its mask by the full-register-rounded
; vector size (16 for the 12 gathered i64s here) while its callers slice by
; the number of scalars (12), pairing mask slices with the wrong matched
; entries and hitting "All elements in mask must be less than 2 * CommonVF"
; in the cost estimation.

target datalayout = "e-p6:32:32-i64:64-i128:128-i256:256-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 16), align 8
; CHECK-NEXT:    [[CONV22_2:%.*]] = trunc i64 [[TMP0]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_2:%.*]] = fptoui half [[TMP1]] to i8
; CHECK-NEXT:    [[ADD24_2:%.*]] = or i8 [[CONV22_2]], [[CONV18_2]]
; CHECK-NEXT:    store i8 [[ADD24_2]], ptr poison, align 2
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 24), align 8
; CHECK-NEXT:    [[CONV22_3:%.*]] = trunc i64 [[TMP2]] to i8
; CHECK-NEXT:    [[TMP3:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_3:%.*]] = fptoui half [[TMP3]] to i8
; CHECK-NEXT:    [[ADD24_3:%.*]] = or i8 [[CONV22_3]], [[CONV18_3]]
; CHECK-NEXT:    store i8 [[ADD24_3]], ptr poison, align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 32), align 8
; CHECK-NEXT:    [[CONV22_4:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP5:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_4:%.*]] = fptoui half [[TMP5]] to i8
; CHECK-NEXT:    [[ADD24_4:%.*]] = or i8 [[CONV22_4]], [[CONV18_4]]
; CHECK-NEXT:    store i8 [[ADD24_4]], ptr poison, align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 40), align 8
; CHECK-NEXT:    [[CONV22_5:%.*]] = trunc i64 [[TMP6]] to i8
; CHECK-NEXT:    [[TMP7:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_5:%.*]] = fptoui half [[TMP7]] to i8
; CHECK-NEXT:    [[ADD24_5:%.*]] = or i8 [[CONV22_5]], [[CONV18_5]]
; CHECK-NEXT:    store i8 [[ADD24_5]], ptr poison, align 1
; CHECK-NEXT:    [[TMP8:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 48), align 8
; CHECK-NEXT:    [[CONV22_6:%.*]] = trunc i64 [[TMP8]] to i8
; CHECK-NEXT:    [[TMP9:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_6:%.*]] = fptoui half [[TMP9]] to i8
; CHECK-NEXT:    [[ADD24_6:%.*]] = or i8 [[CONV22_6]], [[CONV18_6]]
; CHECK-NEXT:    store i8 [[ADD24_6]], ptr poison, align 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 56), align 8
; CHECK-NEXT:    [[CONV22_7:%.*]] = trunc i64 [[TMP10]] to i8
; CHECK-NEXT:    [[TMP11:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_7:%.*]] = fptoui half [[TMP11]] to i8
; CHECK-NEXT:    [[ADD24_7:%.*]] = or i8 [[CONV22_7]], [[CONV18_7]]
; CHECK-NEXT:    store i8 [[ADD24_7]], ptr poison, align 1
; CHECK-NEXT:    [[TMP12:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 64), align 8
; CHECK-NEXT:    [[CONV22_8:%.*]] = trunc i64 [[TMP12]] to i8
; CHECK-NEXT:    [[TMP13:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_8:%.*]] = fptoui half [[TMP13]] to i8
; CHECK-NEXT:    [[ADD24_8:%.*]] = or i8 [[CONV22_8]], [[CONV18_8]]
; CHECK-NEXT:    store i8 [[ADD24_8]], ptr poison, align 8
; CHECK-NEXT:    [[TMP14:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 72), align 8
; CHECK-NEXT:    [[CONV22_9:%.*]] = trunc i64 [[TMP14]] to i8
; CHECK-NEXT:    [[TMP15:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_9:%.*]] = fptoui half [[TMP15]] to i8
; CHECK-NEXT:    [[ADD24_9:%.*]] = or i8 [[CONV22_9]], [[CONV18_9]]
; CHECK-NEXT:    store i8 [[ADD24_9]], ptr poison, align 1
; CHECK-NEXT:    [[TMP16:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 80), align 8
; CHECK-NEXT:    [[CONV22_10:%.*]] = trunc i64 [[TMP16]] to i8
; CHECK-NEXT:    [[TMP17:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_10:%.*]] = fptoui half [[TMP17]] to i8
; CHECK-NEXT:    [[ADD24_10:%.*]] = or i8 [[CONV22_10]], [[CONV18_10]]
; CHECK-NEXT:    store i8 [[ADD24_10]], ptr poison, align 2
; CHECK-NEXT:    [[TMP18:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 88), align 8
; CHECK-NEXT:    [[CONV22_11:%.*]] = trunc i64 [[TMP18]] to i8
; CHECK-NEXT:    [[TMP19:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_11:%.*]] = fptoui half [[TMP19]] to i8
; CHECK-NEXT:    [[ADD24_11:%.*]] = or i8 [[CONV22_11]], [[CONV18_11]]
; CHECK-NEXT:    store i8 [[ADD24_11]], ptr poison, align 1
; CHECK-NEXT:    [[TMP20:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 104), align 8
; CHECK-NEXT:    [[CONV22_13:%.*]] = trunc i64 [[TMP20]] to i8
; CHECK-NEXT:    [[TMP21:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_13:%.*]] = fptoui half [[TMP21]] to i8
; CHECK-NEXT:    [[ADD24_13:%.*]] = or i8 [[CONV22_13]], [[CONV18_13]]
; CHECK-NEXT:    store i8 [[ADD24_13]], ptr poison, align 1
; CHECK-NEXT:    [[TMP22:%.*]] = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 112), align 8
; CHECK-NEXT:    [[CONV22_14:%.*]] = trunc i64 [[TMP22]] to i8
; CHECK-NEXT:    [[TMP23:%.*]] = load half, ptr null, align 2
; CHECK-NEXT:    [[CONV18_14:%.*]] = fptoui half [[TMP23]] to i8
; CHECK-NEXT:    [[ADD24_14:%.*]] = or i8 [[CONV22_14]], [[CONV18_14]]
; CHECK-NEXT:    store i8 [[ADD24_14]], ptr null, align 2
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 16), align 8
  %conv22.2 = trunc i64 %0 to i8
  %1 = load half, ptr null, align 2
  %conv18.2 = fptoui half %1 to i8
  %add24.2 = or i8 %conv22.2, %conv18.2
  store i8 %add24.2, ptr poison, align 2
  %2 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 24), align 8
  %conv22.3 = trunc i64 %2 to i8
  %3 = load half, ptr null, align 2
  %conv18.3 = fptoui half %3 to i8
  %add24.3 = or i8 %conv22.3, %conv18.3
  store i8 %add24.3, ptr poison, align 1
  %4 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 32), align 8
  %conv22.4 = trunc i64 %4 to i8
  %5 = load half, ptr null, align 2
  %conv18.4 = fptoui half %5 to i8
  %add24.4 = or i8 %conv22.4, %conv18.4
  store i8 %add24.4, ptr poison, align 4
  %6 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 40), align 8
  %conv22.5 = trunc i64 %6 to i8
  %7 = load half, ptr null, align 2
  %conv18.5 = fptoui half %7 to i8
  %add24.5 = or i8 %conv22.5, %conv18.5
  store i8 %add24.5, ptr poison, align 1
  %8 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 48), align 8
  %conv22.6 = trunc i64 %8 to i8
  %9 = load half, ptr null, align 2
  %conv18.6 = fptoui half %9 to i8
  %add24.6 = or i8 %conv22.6, %conv18.6
  store i8 %add24.6, ptr poison, align 2
  %10 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 56), align 8
  %conv22.7 = trunc i64 %10 to i8
  %11 = load half, ptr null, align 2
  %conv18.7 = fptoui half %11 to i8
  %add24.7 = or i8 %conv22.7, %conv18.7
  store i8 %add24.7, ptr poison, align 1
  %12 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 64), align 8
  %conv22.8 = trunc i64 %12 to i8
  %13 = load half, ptr null, align 2
  %conv18.8 = fptoui half %13 to i8
  %add24.8 = or i8 %conv22.8, %conv18.8
  store i8 %add24.8, ptr poison, align 8
  %14 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 72), align 8
  %conv22.9 = trunc i64 %14 to i8
  %15 = load half, ptr null, align 2
  %conv18.9 = fptoui half %15 to i8
  %add24.9 = or i8 %conv22.9, %conv18.9
  store i8 %add24.9, ptr poison, align 1
  %16 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 80), align 8
  %conv22.10 = trunc i64 %16 to i8
  %17 = load half, ptr null, align 2
  %conv18.10 = fptoui half %17 to i8
  %add24.10 = or i8 %conv22.10, %conv18.10
  store i8 %add24.10, ptr poison, align 2
  %18 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 88), align 8
  %conv22.11 = trunc i64 %18 to i8
  %19 = load half, ptr null, align 2
  %conv18.11 = fptoui half %19 to i8
  %add24.11 = or i8 %conv22.11, %conv18.11
  store i8 %add24.11, ptr poison, align 1
  %20 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 104), align 8
  %conv22.13 = trunc i64 %20 to i8
  %21 = load half, ptr null, align 2
  %conv18.13 = fptoui half %21 to i8
  %add24.13 = or i8 %conv22.13, %conv18.13
  store i8 %add24.13, ptr poison, align 1
  %22 = load i64, ptr getelementptr inbounds nuw (i8, ptr addrspacecast (ptr addrspace(3) null to ptr), i64 112), align 8
  %conv22.14 = trunc i64 %22 to i8
  %23 = load half, ptr null, align 2
  %conv18.14 = fptoui half %23 to i8
  %add24.14 = or i8 %conv22.14, %conv18.14
  store i8 %add24.14, ptr null, align 2
  ret void
}
