; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=gvn -enable-scalar-pre -S | FileCheck %s --check-prefixes=CHECK,MDEP
; RUN: opt < %s -passes='gvn<memoryssa>' -enable-scalar-pre -S | FileCheck %s --check-prefixes=CHECK,MSSA

@H = common global i32 0
@G = common global i32 0

define i32 @test1(i1 %cond, i32 %v) nounwind {
; CHECK-LABEL: define i32 @test1(
; CHECK-SAME: i1 [[COND:%.*]], i32 [[V:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB:.*]], label %[[BB1:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[ADD_1:%.*]] = add i32 [[V]], 42
; CHECK-NEXT:    store i32 [[ADD_1]], ptr @G, align 4
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = add i32 [[V]], 42
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[ADD_2_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE]], %[[BB1]] ], [ [[ADD_1]], %[[BB]] ]
; CHECK-NEXT:    store i32 [[ADD_2_PRE_PHI]], ptr @H, align 4
; CHECK-NEXT:    ret i32 0
;
entry:
  br i1 %cond, label %bb, label %bb1

bb:
  %add.1 = add nuw nsw i32 %v, 42
  store i32 %add.1, ptr @G, align 4
  br label %return

bb1:
  br label %return

return:
  %add.2 = add i32 %v, 42
  store i32 %add.2, ptr @H, align 4
  ret i32 0
}

define i32 @test2(i1 %cond, i32 %v) nounwind {
; CHECK-LABEL: define i32 @test2(
; CHECK-SAME: i1 [[COND:%.*]], i32 [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB:.*]], label %[[BB1:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[ADD_1:%.*]] = add i32 [[V]], 42
; CHECK-NEXT:    store i32 [[ADD_1]], ptr @G, align 4
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = add i32 [[V]], 42
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[ADD_2_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE]], %[[BB1]] ], [ [[ADD_1]], %[[BB]] ]
; CHECK-NEXT:    store i32 [[ADD_2_PRE_PHI]], ptr @H, align 4
; CHECK-NEXT:    ret i32 0
;
entry:
  br i1 %cond, label %bb, label %bb1

bb:
  %add.1 = add i32 %v, 42
  store i32 %add.1, ptr @G, align 4
  br label %return

bb1:
  br label %return

return:
  %add.2 = add nuw nsw i32 %v, 42
  store i32 %add.2, ptr @H, align 4
  ret i32 0
}

; PRE of %z2 inserts a clone of it on the %entry -> %merge edge.  The clone
; must not keep %z2's nneg: the phi built from it becomes the leader that
; replaces the later flag-free %z3, whose users are NOT poison-tolerant
; (%z2's own poison never escaped its select).
define i32 @test3(i8 %v, i1 %cond, i1 %cond2) {
; CHECK-LABEL: define i32 @test3(
; CHECK-SAME: i8 [[V:%.*]], i1 [[COND:%.*]], i1 [[COND2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB:.*]], label %[[ENTRY_MERGE_CRIT_EDGE:.*]]
; CHECK:       [[ENTRY_MERGE_CRIT_EDGE]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = zext i8 [[V]] to i32
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[Z1:%.*]] = zext i8 [[V]] to i32
; CHECK-NEXT:    store i32 [[Z1]], ptr @G, align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[Z2_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE]], %[[ENTRY_MERGE_CRIT_EDGE]] ], [ [[Z1]], %[[BB]] ]
; CHECK-NEXT:    [[S:%.*]] = select i1 [[COND2]], i32 0, i32 [[Z2_PRE_PHI]]
; CHECK-NEXT:    store i32 [[S]], ptr @H, align 4
; CHECK-NEXT:    ret i32 [[Z2_PRE_PHI]]
;
entry:
  br i1 %cond, label %bb, label %merge

bb:
  %z1 = zext i8 %v to i32
  store i32 %z1, ptr @G, align 4
  br label %merge

merge:
  %z2 = zext nneg i8 %v to i32
  %s = select i1 %cond2, i32 0, i32 %z2
  store i32 %s, ptr @H, align 4
  %z3 = zext i8 %v to i32
  ret i32 %z3
}
; Like test3, but the poison-flagged value the pre-phi picks up is the
; EXISTING %z1 in %bb, not the inserted clone.  %z1 must lose its nneg: a
; second PRE round replaces the flag-free %z3 through the phi (nothing can
; intersect flags through a phi), so on the %bb path %z3's users would see
; %z1's poison, which previously never escaped its select.
define i32 @test4(i8 %v, i1 %cond, i1 %cond2, i1 %cond3) {
; CHECK-LABEL: define i32 @test4(
; CHECK-SAME: i8 [[V:%.*]], i1 [[COND:%.*]], i1 [[COND2:%.*]], i1 [[COND3:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LEFT:.*]], label %[[PRE:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    br i1 [[COND3]], label %[[BB:.*]], label %[[OTHER:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[Z1:%.*]] = zext i8 [[V]] to i32
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[COND2]], i32 0, i32 [[Z1]]
; CHECK-NEXT:    store i32 [[S1]], ptr @G, align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[PRE]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = zext i8 [[V]] to i32
; CHECK-NEXT:    [[DOTPRE1:%.*]] = select i1 [[COND2]], i32 0, i32 [[DOTPRE]]
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[S2_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE1]], %[[PRE]] ], [ [[S1]], %[[BB]] ]
; CHECK-NEXT:    [[Z2_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE]], %[[PRE]] ], [ [[Z1]], %[[BB]] ]
; CHECK-NEXT:    store i32 [[S2_PRE_PHI]], ptr @H, align 4
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    [[DOTPRE2:%.*]] = zext i8 [[V]] to i32
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[Z3_PRE_PHI:%.*]] = phi i32 [ [[DOTPRE2]], %[[OTHER]] ], [ [[Z2_PRE_PHI]], %[[MERGE]] ]
; CHECK-NEXT:    ret i32 [[Z3_PRE_PHI]]
;
entry:
  br i1 %cond, label %left, label %pre

left:
  br i1 %cond3, label %bb, label %other

bb:
  %z1 = zext nneg i8 %v to i32
  %s1 = select i1 %cond2, i32 0, i32 %z1
  store i32 %s1, ptr @G, align 4
  br label %merge

pre:
  br label %merge

merge:
  %z2 = zext nneg i8 %v to i32
  %s2 = select i1 %cond2, i32 0, i32 %z2
  store i32 %s2, ptr @H, align 4
  br label %join

other:
  br label %join

join:
  %z3 = zext i8 %v to i32
  ret i32 %z3
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; MDEP: {{.*}}
; MSSA: {{.*}}
