; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=nvptx64-nvidia-cuda -passes='require<libcall-lowering-info>,atomic-expand' %s | FileCheck %s

; PTX has no atomic instructions for the .local statespace. Local memory is
; thread-private, so atomicrmw and cmpxchg on it are trivially atomic and must
; be expanded to plain loads and stores.

define i32 @atomicrmw_add_local(ptr addrspace(5) %ptr, i32 %val) {
; CHECK-LABEL: define i32 @atomicrmw_add_local(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i32 [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[NEW:%.*]] = add i32 [[TMP1]], [[VAL]]
; CHECK-NEXT:    store i32 [[NEW]], ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %old = atomicrmw add ptr addrspace(5) %ptr, i32 %val monotonic
  ret i32 %old
}

define double @atomicrmw_fadd_local(ptr addrspace(5) %ptr, double %val) {
; CHECK-LABEL: define double @atomicrmw_fadd_local(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], double [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    [[NEW:%.*]] = fadd double [[TMP1]], [[VAL]]
; CHECK-NEXT:    store double [[NEW]], ptr addrspace(5) [[PTR]], align 8
; CHECK-NEXT:    ret double [[TMP1]]
;
  %old = atomicrmw fadd ptr addrspace(5) %ptr, double %val monotonic
  ret double %old
}

define i32 @cmpxchg_local(ptr addrspace(5) %ptr, i32 %cmp, i32 %new) {
; CHECK-LABEL: define i32 @cmpxchg_local(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i32 [[CMP:%.*]], i32 [[NEW:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP1]], [[CMP]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i32 [[NEW]], i32 [[TMP1]]
; CHECK-NEXT:    store i32 [[TMP3]], ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = insertvalue { i32, i1 } poison, i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i32, i1 } [[TMP4]], i1 [[TMP2]], 1
; CHECK-NEXT:    [[OLD:%.*]] = extractvalue { i32, i1 } [[TMP5]], 0
; CHECK-NEXT:    ret i32 [[OLD]]
;
  %pair = cmpxchg ptr addrspace(5) %ptr, i32 %cmp, i32 %new monotonic monotonic
  %old = extractvalue { i32, i1 } %pair, 0
  ret i32 %old
}

; seq_cst is no stronger than monotonic here: nothing can synchronize through
; thread-private memory, so no fences are inserted around the expansion.
define i32 @atomicrmw_add_local_seq_cst(ptr addrspace(5) %ptr, i32 %val) {
; CHECK-LABEL: define i32 @atomicrmw_add_local_seq_cst(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i32 [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    [[NEW:%.*]] = add i32 [[TMP1]], [[VAL]]
; CHECK-NEXT:    store i32 [[NEW]], ptr addrspace(5) [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %old = atomicrmw add ptr addrspace(5) %ptr, i32 %val seq_cst
  ret i32 %old
}

define i8 @cmpxchg_local_i8(ptr addrspace(5) %ptr, i8 %cmp, i8 %new) {
; CHECK-LABEL: define i8 @cmpxchg_local_i8(
; CHECK-SAME: ptr addrspace(5) [[PTR:%.*]], i8 [[CMP:%.*]], i8 [[NEW:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr addrspace(5) [[PTR]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i8 [[TMP1]], [[CMP]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i8 [[NEW]], i8 [[TMP1]]
; CHECK-NEXT:    store i8 [[TMP3]], ptr addrspace(5) [[PTR]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = insertvalue { i8, i1 } poison, i8 [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i8, i1 } [[TMP4]], i1 [[TMP2]], 1
; CHECK-NEXT:    [[OLD:%.*]] = extractvalue { i8, i1 } [[TMP5]], 0
; CHECK-NEXT:    ret i8 [[OLD]]
;
  %pair = cmpxchg ptr addrspace(5) %ptr, i8 %cmp, i8 %new monotonic monotonic
  %old = extractvalue { i8, i1 } %pair, 0
  ret i8 %old
}
