; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -p vector-combine | FileCheck %s

; FIXME: The way we scalarize this today is by creating a
;
; %v = udiv <4 x i8> splat (i8 1), <i8 0, i8 1, i8 1, i8 1>
;
; to insert the scalar into, which is immediate UB.  Coincidentally, at creation
; this gets constant folded into <i8 poison, i8 1, i8 1, i8 1>, but we shouldn't
; rely on this.
define <4 x i8> @udiv_ub(i8 %x, i8 %y) {
; CHECK-LABEL: define <4 x i8> @udiv_ub(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[V_SCALAR:%.*]] = udiv i8 [[X]], [[Y]]
; CHECK-NEXT:    [[V:%.*]] = insertelement <4 x i8> <i8 poison, i8 1, i8 1, i8 1>, i8 [[V_SCALAR]], i64 0
; CHECK-NEXT:    ret <4 x i8> [[V]]
;
  %x.insert = insertelement <4 x i8> splat (i8 1), i8 %x, i32 0
  %y.insert = insertelement <4 x i8> <i8 0, i8 1, i8 1, i8 1>, i8 %y, i32 0
  %v = udiv <4 x i8> %x.insert, %y.insert
  ret <4 x i8> %v
}


; Unfoldable constant expression may cause infinite loop between 
; scalarizing insertelement and folding binop(insert(x,a,idx),insert(y,b,idx))
@val = external hidden global ptr, align 8

define <2 x i64> @pr153012(i64 %idx) #0 {
; CHECK-LABEL: define <2 x i64> @pr153012(
; CHECK-SAME: i64 [[IDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = insertelement <2 x i64> <i64 5, i64 ptrtoint (ptr @val to i64)>, i64 [[IDX]], i32 0
; CHECK-NEXT:    [[B:%.*]] = or disjoint <2 x i64> splat (i64 2), [[A]]
; CHECK-NEXT:    ret <2 x i64> [[B]]
;
entry:
  %a = insertelement <2 x i64> <i64 5, i64 ptrtoint (ptr @val to i64)>, i64 %idx, i32 0
  %b = or disjoint <2 x i64> splat (i64 2), %a
  ret <2 x i64> %b
}

; The scalarized op can fold away: `add %mul, 0` below simplifies to the
; pre-existing %mul. The vector add's nuw/nsw must not be copied onto %mul
; (%x = 0x6d22 overflows %x * %x), nor may %mul be renamed.
define i16 @add_of_mul_flag_transplant(i16 %x) {
; CHECK-LABEL: define i16 @add_of_mul_flag_transplant(
; CHECK-SAME: i16 [[X:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = mul i16 [[X]], [[X]]
; CHECK-NEXT:    [[ADD:%.*]] = insertelement <2 x i16> <i16 poison, i16 2>, i16 [[MUL]], i64 0
; CHECK-NEXT:    [[E:%.*]] = extractelement <2 x i16> [[ADD]], i64 0
; CHECK-NEXT:    ret i16 [[E]]
;
  %mul = mul i16 %x, %x
  %ins = insertelement <2 x i16> <i16 poison, i16 1>, i16 %mul, i64 0
  %add = add nuw nsw <2 x i16> %ins, <i16 0, i16 1>
  %e = extractelement <2 x i16> %add, i64 0
  ret i16 %e
}

; Same with fast-math flags: `fadd %fmul, -0.0` folds to the pre-existing
; %fmul, which must not inherit the fadd's `fast`.
define float @fadd_of_fmul_flag_transplant(float %x) {
; CHECK-LABEL: define float @fadd_of_fmul_flag_transplant(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[FMUL:%.*]] = fmul float [[X]], [[X]]
; CHECK-NEXT:    [[FADD:%.*]] = insertelement <2 x float> <float poison, float 2.000000e+00>, float [[FMUL]], i64 0
; CHECK-NEXT:    [[E:%.*]] = extractelement <2 x float> [[FADD]], i64 0
; CHECK-NEXT:    ret float [[E]]
;
  %fmul = fmul float %x, %x
  %ins = insertelement <2 x float> <float poison, float 1.0>, float %fmul, i64 0
  %fadd = fadd fast <2 x float> %ins, <float -0.0, float 1.0>
  %e = extractelement <2 x float> %fadd, i64 0
  ret float %e
}
