; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck %s

; The i8 sub is widened to s16 with anyext'd operands, so its nuw does not
; hold at 16 bits: %yw's high byte is garbage that can produce a borrow the
; i8 operation never saw. If the legalizer keeps nuw on the wide G_SUB,
; known-bits claims the high byte of the result is zero and the redundant_and
; combine deletes the mask implementing the zext, storing sub garbage. With
; %xw = 10, %yw = 0x0103, %m = 1 this must store 0x0007, not 0xFF07.

define void @widen_sub_nuw_zext_use(i16 %xw, i16 %yw, i16 %m, ptr addrspace(1) %p) {
; CHECK-LABEL: widen_sub_nuw_zext_use:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_and_b32_e32 v0, 15, v0
; CHECK-NEXT:    v_sub_u16_e32 v0, v0, v1
; CHECK-NEXT:    v_mul_lo_u16_sdwa v0, v0, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; CHECK-NEXT:    global_store_short v[3:4], v0, off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %x = trunc i16 %xw to i8
  %y = trunc i16 %yw to i8
  %lhs = and i8 %x, 15
  %sub = sub nuw i8 %lhs, %y
  %z = zext i8 %sub to i16
  %r = mul i16 %z, %m
  store i16 %r, ptr addrspace(1) %p
  ret void
}
