; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64 -O2 < %s | FileCheck %s

; MachineCSE merges the plain `add i32 %x, %y` in %B into the dominating
; `add nsw` from %entry. The survivor must lose its nsw: AArch64's compare
; elision replaces `subs wzr, w8, #0` with the S-form of w8's def only when
; the def has nsw (V-flag users survive the fold, "overflow is poison"), and
; %b made no such promise. With the nsw kept, this compiled to
; `adds w8, w0, w1; csel ..., gt`, and at %x = 0x7fffffff, %y = 1 the adds
; sets N=V=1, GT is true, and the csel picks the mul instead of 7 even though
; the wrapping add and the icmp are fully defined in IR.
; The %q chain only keeps the branch from being if-converted away.

define i32 @add_nsw_twin(i32 %x, i32 %y, i32 %z, i1 %c) {
; CHECK-LABEL: add_nsw_twin:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    tbz w3, #0, .LBB0_2
; CHECK-NEXT:  // %bb.1: // %B
; CHECK-NEXT:    add w8, w0, w1
; CHECK-NEXT:    mul w9, w8, w2
; CHECK-NEXT:    cmp w8, #0
; CHECK-NEXT:    mov w8, #7 // =0x7
; CHECK-NEXT:    csel w8, w9, w8, gt
; CHECK-NEXT:    mov w9, #42 // =0x2a
; CHECK-NEXT:    mul w8, w8, w2
; CHECK-NEXT:    eor w0, w8, w9
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
entry:
  %a = add nsw i32 %x, %y
  br i1 %c, label %B, label %C

B:
  %m = mul i32 %a, %z
  %b = add i32 %x, %y
  %cmp = icmp sgt i32 %b, 0
  %s = select i1 %cmp, i32 %m, i32 7
  %q1 = mul i32 %s, %z
  %q2 = xor i32 %q1, 42
  ret i32 %q2

C:
  ret i32 0
}
