; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -passes=instcombine -S | FileCheck %s

; Simplify to +0.0 + z.
define float @test_zero(float %x, float %z) {
; CHECK-LABEL: @test_zero(
; CHECK-NEXT:    [[CALL:%.*]] = fadd float [[Z:%.*]], 0.000000e+00
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float 0.0, float %z)
  ret float %call
}

; Simplify to +0.0 + z, preserving fmf.
define float @test_zero_fmf(float %x, float %z) {
; CHECK-LABEL: @test_zero_fmf(
; CHECK-NEXT:    [[CALL:%.*]] = fadd contract float [[Z:%.*]], 0.000000e+00
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call contract float @llvm.amdgcn.fma.legacy(float %x, float 0.0, float %z)
  ret float %call
}

; Simplify to z.
define float @test_zero_nsz(float %x, float %z) {
; CHECK-LABEL: @test_zero_nsz(
; CHECK-NEXT:    ret float [[Z:%.*]]
;
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %x, float 0.0, float %z)
  ret float %call
}

; Simplify to +0.0 + z.
define float @test_negzero(float %y, float %z) {
; CHECK-LABEL: @test_negzero(
; CHECK-NEXT:    [[CALL:%.*]] = fadd float [[Z:%.*]], 0.000000e+00
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float -0.0, float %y, float %z)
  ret float %call
}

; Simplify to z.
define float @test_negzero_nsz(float %y, float %z) {
; CHECK-LABEL: @test_negzero_nsz(
; CHECK-NEXT:    ret float [[Z:%.*]]
;
  %call = call nsz float @llvm.amdgcn.fma.legacy(float -0.0, float %y, float %z)
  ret float %call
}

; Do not combine to fma: if %x is -0.0 the intrinsic multiplies by +0.0 but
; fma multiplies by -0.0.
define float @test_const(float %x, float %z) {
; CHECK-LABEL: @test_const(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.amdgcn.fma.legacy(float [[X:%.*]], float 9.950000e+01, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float 99.5, float %z)
  ret float %call
}

; Combine to fma because the constant is finite and non-zero and nsz allows
; either sign for a zero product.
define float @test_const_nsz(float %x, float %z) {
; CHECK-LABEL: @test_const_nsz(
; CHECK-NEXT:    [[CALL:%.*]] = call nsz float @llvm.fma.f32(float [[X:%.*]], float 9.950000e+01, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %x, float 99.5, float %z)
  ret float %call
}

; Combine to fma because the constant is finite and non-zero and %x cannot
; be a zero.
define float @test_const_nonzero(float nofpclass(zero) %x, float %z) {
; CHECK-LABEL: @test_const_nonzero(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.fma.f32(float [[X:%.*]], float 9.950000e+01, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float 99.5, float %z)
  ret float %call
}

; Do not combine to fma: same as test_const with the constant as the first
; operand.
define float @test_const_op0(float %x, float %z) {
; CHECK-LABEL: @test_const_op0(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.amdgcn.fma.legacy(float 9.950000e+01, float [[X:%.*]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float 99.5, float %x, float %z)
  ret float %call
}

; Combine to fma because the constant (as the first operand) is finite and
; non-zero and %x cannot be a zero.
define float @test_const_op0_nonzero(float nofpclass(zero) %x, float %z) {
; CHECK-LABEL: @test_const_op0_nonzero(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.fma.f32(float [[X:%.*]], float 9.950000e+01, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float 99.5, float %x, float %z)
  ret float %call
}

; Combine to fma, preserving fmf.
define float @test_const_fmf(float %x, float %z) {
; CHECK-LABEL: @test_const_fmf(
; CHECK-NEXT:    [[CALL:%.*]] = call nsz contract float @llvm.fma.f32(float [[X:%.*]], float 9.950000e+01, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call contract nsz float @llvm.amdgcn.fma.legacy(float %x, float 99.5, float %z)
  ret float %call
}

; Do not combine to fma: %xf can be +0.0 while %yf is negative, where the
; intrinsic multiplies by +0.0 but fma gives a -0.0 product.
define float @test_finite(i32 %x, i32 %y, float %z) {
; CHECK-LABEL: @test_finite(
; CHECK-NEXT:    [[XF:%.*]] = sitofp i32 [[X:%.*]] to float
; CHECK-NEXT:    [[YF:%.*]] = sitofp i32 [[Y:%.*]] to float
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.amdgcn.fma.legacy(float [[XF]], float [[YF]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %xf = sitofp i32 %x to float
  %yf = sitofp i32 %y to float
  %call = call float @llvm.amdgcn.fma.legacy(float %xf, float %yf, float %z)
  ret float %call
}

; Combine to fma because neither argument can be infinity or NaN and nsz
; allows either sign for a zero product.
define float @test_finite_nsz(i32 %x, i32 %y, float %z) {
; CHECK-LABEL: @test_finite_nsz(
; CHECK-NEXT:    [[XF:%.*]] = sitofp i32 [[X:%.*]] to float
; CHECK-NEXT:    [[YF:%.*]] = sitofp i32 [[Y:%.*]] to float
; CHECK-NEXT:    [[CALL:%.*]] = call nsz float @llvm.fma.f32(float [[XF]], float [[YF]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %xf = sitofp i32 %x to float
  %yf = sitofp i32 %y to float
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %xf, float %yf, float %z)
  ret float %call
}

; Combine to fma because neither argument can be infinity, NaN or zero.
define float @test_finite_nonzero(float nofpclass(nan inf zero) %x, float nofpclass(nan inf zero) %y, float %z) {
; CHECK-LABEL: @test_finite_nonzero(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.fma.f32(float [[X:%.*]], float [[Y:%.*]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float %y, float %z)
  ret float %call
}

; Do not combine to fma without nsz: the multiplied arguments are finite but
; either could be a zero.
define float @test_finite_assumed(float %x, float %y, float %z) {
; CHECK-LABEL: @test_finite_assumed(
; CHECK-NEXT:    [[FABS_X:%.*]] = call float @llvm.fabs.f32(float [[X:%.*]])
; CHECK-NEXT:    [[IS_FINITE_X:%.*]] = fcmp one float [[FABS_X]], +inf
; CHECK-NEXT:    [[FABS_Y:%.*]] = call float @llvm.fabs.f32(float [[Y:%.*]])
; CHECK-NEXT:    [[IS_FINITE_Y:%.*]] = fcmp one float [[FABS_Y]], +inf
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_FINITE_X]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_FINITE_Y]])
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.amdgcn.fma.legacy(float [[X]], float [[Y]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %fabs.x = call float @llvm.fabs.f32(float %x)
  %is.finite.x = fcmp one float %fabs.x, 0x7FF0000000000000
  %fabs.y = call float @llvm.fabs.f32(float %y)
  %is.finite.y = fcmp one float %fabs.y, 0x7FF0000000000000
  call void @llvm.assume(i1 %is.finite.x)
  call void @llvm.assume(i1 %is.finite.y)
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float %y, float %z)
  ret float %call
}

; Combine to fma because neither argument can be infinity or NaN and nsz
; allows either sign for a zero product.
define float @test_finite_assumed_nsz(float %x, float %y, float %z) {
; CHECK-LABEL: @test_finite_assumed_nsz(
; CHECK-NEXT:    [[FABS_X:%.*]] = call float @llvm.fabs.f32(float [[X:%.*]])
; CHECK-NEXT:    [[IS_FINITE_X:%.*]] = fcmp one float [[FABS_X]], +inf
; CHECK-NEXT:    [[FABS_Y:%.*]] = call float @llvm.fabs.f32(float [[Y:%.*]])
; CHECK-NEXT:    [[IS_FINITE_Y:%.*]] = fcmp one float [[FABS_Y]], +inf
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_FINITE_X]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_FINITE_Y]])
; CHECK-NEXT:    [[CALL:%.*]] = call nsz float @llvm.fma.f32(float [[X]], float [[Y]], float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %fabs.x = call float @llvm.fabs.f32(float %x)
  %is.finite.x = fcmp one float %fabs.x, 0x7FF0000000000000
  %fabs.y = call float @llvm.fabs.f32(float %y)
  %is.finite.y = fcmp one float %fabs.y, 0x7FF0000000000000
  call void @llvm.assume(i1 %is.finite.x)
  call void @llvm.assume(i1 %is.finite.y)
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %x, float %y, float %z)
  ret float %call
}

; Do not combine to fma: input denormals are flushed, so the denormal
; constant is itself a logical zero and %x could be infinity, where the
; intrinsic multiplies by +0.0 but fma gives NaN.
define float @test_denormal_const_flush(float %x, float %z) #0 {
; CHECK-LABEL: @test_denormal_const_flush(
; CHECK-NEXT:    [[CALL:%.*]] = call nsz float @llvm.amdgcn.fma.legacy(float [[X:%.*]], float f0x00400000, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %x, float 0x3800000000000000, float %z)
  ret float %call
}

; Do not combine to fma: same as test_denormal_const_flush without nsz.
define float @test_denormal_const_flush_nonsz(float %x, float %z) #0 {
; CHECK-LABEL: @test_denormal_const_flush_nonsz(
; CHECK-NEXT:    [[CALL:%.*]] = call float @llvm.amdgcn.fma.legacy(float [[X:%.*]], float f0x00400000, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float 0x3800000000000000, float %z)
  ret float %call
}

; Combine to fma: without flushing the denormal constant is an ordinary
; finite non-zero value.
define float @test_denormal_const_ieee(float %x, float %z) {
; CHECK-LABEL: @test_denormal_const_ieee(
; CHECK-NEXT:    [[CALL:%.*]] = call nsz float @llvm.fma.f32(float [[X:%.*]], float f0x00400000, float [[Z:%.*]])
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call nsz float @llvm.amdgcn.fma.legacy(float %x, float 0x3800000000000000, float %z)
  ret float %call
}

define float @test_poison_x_y(float %x, float %y) {
; CHECK-LABEL: @test_poison_x_y(
; CHECK-NEXT:    ret float poison
;
  %call = call float @llvm.amdgcn.fma.legacy(float poison, float %x, float %y)
  ret float %call
}

define float @test_x_poison_y(float %x, float %y) {
; CHECK-LABEL: @test_x_poison_y(
; CHECK-NEXT:    ret float poison
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float poison, float %y)
  ret float %call
}

define float @test_x_y_poison_y(float %x, float %y) {
; CHECK-LABEL: @test_x_y_poison_y(
; CHECK-NEXT:    ret float poison
;
  %call = call float @llvm.amdgcn.fma.legacy(float %x, float %y, float poison)
  ret float %call
}

declare float @llvm.amdgcn.fma.legacy(float, float, float)
declare float @llvm.fabs.f32(float)
declare void @llvm.assume(i1 noundef)

attributes #0 = { denormal_fpenv(ieee|preservesign) }
