; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=nvptx64-nvidia-cuda -passes=load-store-vectorizer -S -o - %s | FileCheck %s

; getConstantOffsetComplexAddrs proves the two narrow indices differ by
; IdxDiff, then multiplies IdxDiff by the element stride to get the byte
; distance.  The multiply must be done at the pointer index width: at the
; narrow (i32) index width, IdxDiff = 2^30 times stride 4 wraps to 0, making
; two loads that are 2^32 bytes apart look like the same address.
;
; SCEV can't prove the flagless adds don't overflow (the assume has no context
; instruction there), so the i32 tests go through the known-bits path.

declare void @llvm.assume(i1)

@table = private constant [4 x i64] [i64 0, i64 1, i64 2, i64 3]

define void @sext_wrap_to_zero(ptr %base, i32 %x, ptr %out) {
; CHECK-LABEL: define void @sext_wrap_to_zero(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X]], 256
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[B:%.*]] = add i32 [[X]], 1073741824
; CHECK-NEXT:    [[SX:%.*]] = sext i32 [[X]] to i64
; CHECK-NEXT:    [[SB:%.*]] = sext i32 [[B]] to i64
; CHECK-NEXT:    [[GEPA:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[SX]]
; CHECK-NEXT:    [[GEPB:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[SB]]
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[GEPA]], align 8
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[GEPB]], align 4
; CHECK-NEXT:    store i32 [[L1]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[L2]], ptr [[OUT2]], align 4
; CHECK-NEXT:    ret void
;
  %cmp = icmp ult i32 %x, 256
  call void @llvm.assume(i1 %cmp)
  %b = add i32 %x, 1073741824       ; x + 2^30, no nsw
  %sx = sext i32 %x to i64
  %sb = sext i32 %b to i64
  %gepA = getelementptr inbounds i32, ptr %base, i64 %sx
  %gepB = getelementptr inbounds i32, ptr %base, i64 %sb
  %l1 = load i32, ptr %gepA, align 8
  %l2 = load i32, ptr %gepB, align 4
  store i32 %l1, ptr %out
  %out2 = getelementptr i32, ptr %out, i64 1
  store i32 %l2, ptr %out2
  ret void
}

define void @sext_wrap_to_four(ptr %base, i32 %x, ptr %out) {
; CHECK-LABEL: define void @sext_wrap_to_four(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X]], 256
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[B:%.*]] = add i32 [[X]], 1073741825
; CHECK-NEXT:    [[SX:%.*]] = sext i32 [[X]] to i64
; CHECK-NEXT:    [[SB:%.*]] = sext i32 [[B]] to i64
; CHECK-NEXT:    [[GEPA:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[SX]]
; CHECK-NEXT:    [[GEPB:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[SB]]
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[GEPA]], align 8
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[GEPB]], align 4
; CHECK-NEXT:    store i32 [[L1]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[L2]], ptr [[OUT2]], align 4
; CHECK-NEXT:    ret void
;
  %cmp = icmp ult i32 %x, 256
  call void @llvm.assume(i1 %cmp)
  %b = add i32 %x, 1073741825       ; x + 2^30 + 1, no nsw
  %sx = sext i32 %x to i64
  %sb = sext i32 %b to i64
  %gepA = getelementptr inbounds i32, ptr %base, i64 %sx
  %gepB = getelementptr inbounds i32, ptr %base, i64 %sb
  %l1 = load i32, ptr %gepA, align 8
  %l2 = load i32, ptr %gepB, align 4
  store i32 %l1, ptr %out
  %out2 = getelementptr i32, ptr %out, i64 1
  store i32 %l2, ptr %out2
  ret void
}

define void @zext_wrap_to_zero(ptr %base, i32 %x, ptr %out) {
; CHECK-LABEL: define void @zext_wrap_to_zero(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X]], 256
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[B:%.*]] = add i32 [[X]], 1073741824
; CHECK-NEXT:    [[ZX:%.*]] = zext i32 [[X]] to i64
; CHECK-NEXT:    [[ZB:%.*]] = zext i32 [[B]] to i64
; CHECK-NEXT:    [[GEPA:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[ZX]]
; CHECK-NEXT:    [[GEPB:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[ZB]]
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[GEPA]], align 8
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[GEPB]], align 4
; CHECK-NEXT:    store i32 [[L1]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[L2]], ptr [[OUT2]], align 4
; CHECK-NEXT:    ret void
;
  %cmp = icmp ult i32 %x, 256
  call void @llvm.assume(i1 %cmp)
  %b = add i32 %x, 1073741824       ; x + 2^30, no nuw
  %zx = zext i32 %x to i64
  %zb = zext i32 %b to i64
  %gepA = getelementptr inbounds i32, ptr %base, i64 %zx
  %gepB = getelementptr inbounds i32, ptr %base, i64 %zb
  %l1 = load i32, ptr %gepA, align 8
  %l2 = load i32, ptr %gepB, align 4
  store i32 %l1, ptr %out
  %out2 = getelementptr i32, ptr %out, i64 1
  store i32 %l2, ptr %out2
  ret void
}

; SimplifyCFG switch lookup tables index the table with the switch
; condition's own type, so the index can be narrower than the stride: with an
; i2 index and stride 8, even IdxDiff = -1 wraps to 0 in the i2 multiply
; (-1 * 8 == -8 == 0 mod 4), and the two table loads look like the same
; address.  No large constants involved, and a different no-wrap proof: SCEV
; computes the singleton IdxDiff ((t+1) - (t^-2) == -1 mod 4), and the
; SCEV unsigned-range check proves safety from t being a two-bit
; sign-extension ({0,-1}), where known bits see nothing through trunc(ashr).
; With the fix the loads are correctly seen 8 bytes apart; they stay scalar
; only because NVPTX rejects the 16-byte access at align 8 -- the property
; under test is that both loads survive.

define void @zext_i2_switch_table(i16 %x, ptr %out) {
; CHECK-LABEL: define void @zext_i2_switch_table(
; CHECK-SAME: i16 [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[S:%.*]] = ashr i16 [[X]], 15
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[S]] to i2
; CHECK-NEXT:    [[A:%.*]] = xor i2 [[T]], -2
; CHECK-NEXT:    [[ZA:%.*]] = zext i2 [[A]] to i64
; CHECK-NEXT:    [[GEPA:%.*]] = getelementptr [8 x i8], ptr @table, i64 [[ZA]]
; CHECK-NEXT:    [[LA:%.*]] = load i64, ptr [[GEPA]], align 8
; CHECK-NEXT:    [[B:%.*]] = add i2 [[T]], 1
; CHECK-NEXT:    [[ZB:%.*]] = zext i2 [[B]] to i64
; CHECK-NEXT:    [[GEPB:%.*]] = getelementptr [8 x i8], ptr @table, i64 [[ZB]]
; CHECK-NEXT:    [[LB:%.*]] = load i64, ptr [[GEPB]], align 8
; CHECK-NEXT:    store i64 [[LA]], ptr [[OUT]], align 8
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i8, ptr [[OUT]], i64 8
; CHECK-NEXT:    store i64 [[LB]], ptr [[OUT2]], align 8
; CHECK-NEXT:    ret void
;
  %s = ashr i16 %x, 15
  %t = trunc i16 %s to i2
  %a = xor i2 %t, -2
  %za = zext i2 %a to i64
  %gepA = getelementptr [8 x i8], ptr @table, i64 %za
  %la = load i64, ptr %gepA, align 8
  %b = add i2 %t, 1
  %zb = zext i2 %b to i64
  %gepB = getelementptr [8 x i8], ptr @table, i64 %zb
  %lb = load i64, ptr %gepB, align 8
  store i64 %la, ptr %out
  %out2 = getelementptr i8, ptr %out, i64 8
  store i64 %lb, ptr %out2
  ret void
}

; Control: a small index delta through the same known-bits path must still
; vectorize.

define void @sext_small_delta(ptr %base, i32 %x, ptr %out) {
; CHECK-LABEL: define void @sext_small_delta(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X]], 256
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[SX:%.*]] = sext i32 [[X]] to i64
; CHECK-NEXT:    [[GEPA:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[SX]]
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[GEPA]], align 8
; CHECK-NEXT:    [[L11:%.*]] = extractelement <2 x i32> [[TMP1]], i32 0
; CHECK-NEXT:    [[L22:%.*]] = extractelement <2 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    store i32 [[L11]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[L22]], ptr [[OUT2]], align 4
; CHECK-NEXT:    ret void
;
  %cmp = icmp ult i32 %x, 256
  call void @llvm.assume(i1 %cmp)
  %b = add i32 %x, 1                ; no nsw
  %sx = sext i32 %x to i64
  %sb = sext i32 %b to i64
  %gepA = getelementptr inbounds i32, ptr %base, i64 %sx
  %gepB = getelementptr inbounds i32, ptr %base, i64 %sb
  %l1 = load i32, ptr %gepA, align 8
  %l2 = load i32, ptr %gepB, align 4
  store i32 %l1, ptr %out
  %out2 = getelementptr i32, ptr %out, i64 1
  store i32 %l2, ptr %out2
  ret void
}
